name: Deploy ZIP to GitHub Pages

on:
  push:
    branches: ['master']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dashboard code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: pnpm

      - name: Install package and build
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build

      - name: Create ZIP from public/
        run: |
          cd public
          zip -r ../site.zip .

      - name: Prepare Pages folder
        run: |
          mkdir -p pages
          mv dashboard.zip pages/dashboard.zip

          cat > pages/index.html <<'EOF'
          <!doctype html>
          <meta charset="utf-8" />
          <title>Download</title>
          <a href="./dashboard.zip">Download dashboard.zip</a>
          EOF

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
